FROM golang:latest AS builder

WORKDIR /build

COPY . .

RUN go get -u "github.com/go-sql-driver/mysql"

RUN go build cmd/app/main.go

FROM golang:latest AS RUNNER

COPY --from=builder /build/main ./main

ENTRYPOINT ["./main"]
