CREATE DATABASE IF NOT EXISTS todo;

CREATE TABLE IF NOT EXISTS `todo`.`todos` (
    id INT NOT NULL AUTO_INCREMENT,
    todo VARCHAR(255) NOT NULL,
    date DATETIME NOT NULL,
    urgency INT NOT NULL,
    is_done INT DEFAULT 0,
    is_deleted INT DEFAULT 0,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS `todo`.`users` (
    id VARCHAR(32) NOT NULL DEFAULT (UUID()),
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE IF NOT EXISTS `todo`.`sessions` (
    id VARCHAR(32) NOT NULL DEFAULT (UUID()),
    userId VARCHAR(255) NOT NULL,
    FOREIGN KEY (userId) REFRENCES `todo`.`users`(id)
)

CREATE USER IF NOT EXISTS chenzadik;

GRANT ALL PRIVILEGES ON todo.* TO 'chenzadik'@'localhost';

FLUSH PRIVILEGES;