CREATE TABLE IF NOT EXISTS `todo`.`users` (
    id VARCHAR(128) NOT NULL DEFAULT (UUID()),
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS `todo`.`todos` (
    id INT NOT NULL AUTO_INCREMENT,
    todo VARCHAR(255) NOT NULL,
    userId VARCHAR(128) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    date DATETIME NOT NULL,
    urgency INT NOT NULL,
    is_done INT DEFAULT 0,
    is_deleted INT DEFAULT 0,
    PRIMARY KEY(id),
    FOREIGN KEY (userId) REFERENCES `todo`.`users`(id)
);

CREATE TABLE IF NOT EXISTS `todo`.`sessions` (
    id VARCHAR(128) NOT NULL DEFAULT (UUID()),
    userId VARCHAR(128) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES `todo`.`users`(id)
);