version: '3'

services:
  mysql:
    image: 705252976650.dkr.ecr.il-central-1.amazonaws.com/todo-app:db-prod
    build:
        dockerfile: Dockerfile.db
    container_name: db-prod
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE_FILE: /run/secrets/db_database
      MYSQL_USER_FILE: /run/secrets/db_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_root_password
      - db_database
      - db_user
      - db_password
    volumes:
      - ./mysql-scripts:/docker-entrypoint-initdb.d/
      - mysql-data:/var/lib/mysql

  server:
    image: 705252976650.dkr.ecr.il-central-1.amazonaws.com/todo-app:server-prod
    build:
      context: ../../backend/
      dockerfile: ../docker/production/Dockerfile.server
    container_name: server-prod
    ports:
      - '8080:8080'
    depends_on:
      - mysql
    environment:
      DB_DATABASE_FILE: /run/secrets/db_database
      DB_USER_FILE: /run/secrets/db_user
      DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_database
      - db_user
      - db_password

  app:
    image: 705252976650.dkr.ecr.il-central-1.amazonaws.com/todo-app:app-prod
    build:
      context: ../../frontend/
      dockerfile: ../docker/production/Dockerfile.app
    container_name: app-prod
    environment:
      - PORT=80
    ports:
      - '80:80'
    depends_on:
      - server
    
volumes:
  mysql-data:

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_database:
    file: ./secrets/db_database.txt
  db_user:
    file: ./secrets/db_user.txt
  db_root_password:
    file: ./secrets/db_root_password.txt
    